# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coordinate_rotate <- function(coords, theta) {
    .Call(`_GWmodelFE_coordinate_rotate`, coords, theta)
}

eu_dist_mat <- function(in_locs, out_locs) {
    .Call(`_GWmodelFE_eu_dist_mat`, in_locs, out_locs)
}

eu_dist_smat <- function(in_locs) {
    .Call(`_GWmodelFE_eu_dist_smat`, in_locs)
}

eu_dist_vec <- function(in_locs, out_loc) {
    .Call(`_GWmodelFE_eu_dist_vec`, in_locs, out_loc)
}

md_dist_mat <- function(in_locs, out_locs) {
    .Call(`_GWmodelFE_md_dist_mat`, in_locs, out_locs)
}

md_dist_smat <- function(in_locs) {
    .Call(`_GWmodelFE_md_dist_smat`, in_locs)
}

md_dist_vec <- function(in_locs, out_loc) {
    .Call(`_GWmodelFE_md_dist_vec`, in_locs, out_loc)
}

cd_dist_mat <- function(in_locs, out_locs) {
    .Call(`_GWmodelFE_cd_dist_mat`, in_locs, out_locs)
}

cd_dist_smat <- function(in_locs) {
    .Call(`_GWmodelFE_cd_dist_smat`, in_locs)
}

cd_dist_vec <- function(in_locs, out_loc) {
    .Call(`_GWmodelFE_cd_dist_vec`, in_locs, out_loc)
}

mk_dist_mat <- function(in_locs, out_locs, p) {
    .Call(`_GWmodelFE_mk_dist_mat`, in_locs, out_locs, p)
}

mk_dist_smat <- function(in_locs, p) {
    .Call(`_GWmodelFE_mk_dist_smat`, in_locs, p)
}

mk_dist_vec <- function(in_locs, out_loc, p) {
    .Call(`_GWmodelFE_mk_dist_vec`, in_locs, out_loc, p)
}

bisq_wt_vec <- function(distv, bw) {
    .Call(`_GWmodelFE_bisq_wt_vec`, distv, bw)
}

bisq_wt_mat <- function(distm, bw) {
    .Call(`_GWmodelFE_bisq_wt_mat`, distm, bw)
}

gauss_wt_vec <- function(distv, bw) {
    .Call(`_GWmodelFE_gauss_wt_vec`, distv, bw)
}

gauss_wt_mat <- function(distm, bw) {
    .Call(`_GWmodelFE_gauss_wt_mat`, distm, bw)
}

tri_wt_vec <- function(distv, bw) {
    .Call(`_GWmodelFE_tri_wt_vec`, distv, bw)
}

tri_wt_mat <- function(distm, bw) {
    .Call(`_GWmodelFE_tri_wt_mat`, distm, bw)
}

exp_wt_vec <- function(distv, bw) {
    .Call(`_GWmodelFE_exp_wt_vec`, distv, bw)
}

exp_wt_mat <- function(distm, bw) {
    .Call(`_GWmodelFE_exp_wt_mat`, distm, bw)
}

gw_reg <- function(x, y, w, hatmatrix, focus) {
    .Call(`_GWmodelFE_gw_reg`, x, y, w, hatmatrix, focus)
}

trhat2 <- function(S) {
    .Call(`_GWmodelFE_trhat2`, S)
}

fitted <- function(X, beta) {
    .Call(`_GWmodelFE_fitted`, X, beta)
}

ehat <- function(y, X, beta) {
    .Call(`_GWmodelFE_ehat`, y, X, beta)
}

rss <- function(y, X, beta) {
    .Call(`_GWmodelFE_rss`, y, X, beta)
}

gwr_diag <- function(y, x, beta, S) {
    .Call(`_GWmodelFE_gwr_diag`, y, x, beta, S)
}

gwr_diag1 <- function(y, x, beta, s_hat) {
    .Call(`_GWmodelFE_gwr_diag1`, y, x, beta, s_hat)
}

AICc <- function(y, x, beta, S) {
    .Call(`_GWmodelFE_AICc`, y, x, beta, S)
}

AICc1 <- function(y, x, beta, s_hat) {
    .Call(`_GWmodelFE_AICc1`, y, x, beta, s_hat)
}

AICc_rss <- function(y, x, beta, S) {
    .Call(`_GWmodelFE_AICc_rss`, y, x, beta, S)
}

Ci_mat <- function(x, w) {
    .Call(`_GWmodelFE_Ci_mat`, x, w)
}

scgwr_pre <- function(x, y, bw, poly, b0, g0, neighbour) {
    .Call(`_GWmodelFE_scgwr_pre`, x, y, bw, poly, b0, g0, neighbour)
}

scgwr_loocv <- function(target, x, y, bw, poly, Mx0, My0, XtX, XtY) {
    .Call(`_GWmodelFE_scgwr_loocv`, target, x, y, bw, poly, Mx0, My0, XtX, XtY)
}

scgwr_reg <- function(x, y, bw, poly, G0, Mx0, My0, XtX, XtY, neighbour, parameters) {
    .Call(`_GWmodelFE_scgwr_reg`, x, y, bw, poly, G0, Mx0, My0, XtX, XtY, neighbour, parameters)
}

box_wt_vec <- function(distv, bw) {
    .Call(`_GWmodelFE_box_wt_vec`, distv, bw)
}

box_wt_vec_ad <- function(distv, bw) {
    .Call(`_GWmodelFE_box_wt_vec_ad`, distv, bw)
}

gau_wt_vec_ad <- function(distv, bw) {
    .Call(`_GWmodelFE_gau_wt_vec_ad`, distv, bw)
}

bis_wt_vec_ad <- function(distv, bw) {
    .Call(`_GWmodelFE_bis_wt_vec_ad`, distv, bw)
}

tri_wt_vec_ad <- function(distv, bw) {
    .Call(`_GWmodelFE_tri_wt_vec_ad`, distv, bw)
}

exp_wt_vec_ad <- function(distv, bw) {
    .Call(`_GWmodelFE_exp_wt_vec_ad`, distv, bw)
}

gw_weight <- function(vdist, bw, kernel, adaptive) {
    .Call(`_GWmodelFE_gw_weight`, vdist, bw, kernel, adaptive)
}

gw_reg_2 <- function(x, y, w) {
    .Call(`_GWmodelFE_gw_reg_2`, x, y, w)
}

gwr_q <- function(x, y, dMat, bw, kernel, adaptive) {
    .Call(`_GWmodelFE_gwr_q`, x, y, dMat, bw, kernel, adaptive)
}

e_vec <- function(m, n) {
    .Call(`_GWmodelFE_e_vec`, m, n)
}

gwr_mixed_trace <- function(x1, x2, y, dMat, bw, kernel, adaptive) {
    .Call(`_GWmodelFE_gwr_mixed_trace`, x1, x2, y, dMat, bw, kernel, adaptive)
}

gwr_mixed_2 <- function(x1, x2, y, dMat, bw, kernel, adaptive) {
    .Call(`_GWmodelFE_gwr_mixed_2`, x1, x2, y, dMat, bw, kernel, adaptive)
}

